version: '3.8'

services:
  dsproxy-backend:
    build:
      context: ./dsproxy-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./dsproxy-backend/config.yaml:/app/config.yaml
    depends_on:
      - postgres
    restart: unless-stopped

  dsproxy-controller:
    build:
      context: .
      dockerfile: ./dsproxy-controller/Dockerfile
    depends_on:
      - dsproxy-backend
    volumes:
      - ./keypairs/bot.demo.json:/app/data/solana-keypair
    restart: unless-stopped

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: dephy
      POSTGRES_PASSWORD: dephy
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./dsproxy-backend/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres-data: