auth:
  secret: "dephy"
  exp_hour: 720

database:
  host: "localhost"
  user: "postgres"
  password: "your_password"
  dbname: "your_db"
  port: "5432"
  sslmode: "disable"

nostr:
  session: "dephy-dsproxy-controller"
  relay_url: "ws://127.0.0.1:8000"
  machine_pubkey: "d041ea9854f2117b82452457c4e6d6593a96524027cd4032d2f40046deb78d93"

chat:
  api_key: "api_key"
  max_context_tokens: 65536
  
server:
  port: 8080  